server:
  port: 8080

spring:
  application:
    name: website.rest.api
  datasource:
    url: jdbc:mysql://mysql:3306/eshop_db_new?createDatabaseIfNotExist=true
    username: root
    password: stindadh
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update